In [1]:
#importing the libraries 

In [2]:
import numpy as np #work with arrays 
import matplotlib.pyplot as plt #lib to allow us plot 
import pandas as pd #import dataset and create matrics

In [3]:
#import dataset

In [5]:
dataset=pd.read_csv('Data.csv') #Pandas function which read all data from csv and create dataframe
#In any dataset there will be feature - column with which v predict the depentent variable and depentent variable is what u want to predict
x = dataset.iloc[:, :-1].values  #feature.iloc to get data : range which takes all rows , :-1 range which take all columns other than the last column. This will take indices from all rows from 1st 3 columns
y = dataset.iloc[:, -1].values  # depentant variable. Index of last column

In [6]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [7]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [8]:
#taking care of missing data 

In [9]:
# 1. ignore data by deleting it. OK if 1% of data is impacted
# 2. replace missing value with ave of all other column data 

In [11]:
from sklearn.impute import SimpleImputer # import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean') # varibale to create object of SimpleImputer and alllow to replace missing sal with ave of all other sal
imputer.fit(x[:,1:3])#look for missing values and cal ave
x[:,1:3]=imputer.transform(x[:,1:3]) #replace missign val with calulated value in 1st(age) and 2nd(salary) cols

In [12]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [13]:
#encoding categorical data

In [14]:
#one hot encoding turn country columns to 3(as there are 3 countires).It created binary vector for each country so that there is no order between these countries- France vector 1,0,0 Spain 0,1,0 and Germany 0,0,1
#replace purchased col with 0 and 1 

In [17]:
#encoding independent variable 

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough') # Apply tranformation to change country to binary vector  Remainder keep age and salary 
x = np.array(ct.fit_transform(x)) #fitting and transforming together and force output to be numpy array 
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [18]:
#encoding dependent variable 

In [21]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y= le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [22]:
#splitting the dataset into training and test set  

In [23]:
# apply feature scaling after splitting the dataset. Test set is supposed to be new data set. Feature scaling will get mean and median of the data so its better to apply this before splitting data so to avoid data leakage   

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 1) # func returns train and test data. It takes dataset and then split size test_size =0.2 means 20% data is for test and rest for training and random_state 


In [25]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [26]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [27]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [28]:
print(y_test)

[0 1]


In [29]:
#feature scaling - not all models need this to be applied

In [30]:
#Main two feature scaling techniques are standardisation and normalisation
#Xstan =(x - mean(x))/(standard deviation(x)) -- o/p values between -3 and +3
#Xnorm =(x - min(x))/(max(x) - min(x)) -- o/p values between 0 and 1
#normalisation is recommended to be used for normal distribution while standardisation works well all the time. So better to go for standardisation.
#We do not need to apply feature scaling on dummy variables as they are already encoding to 0 or 1 or binary vector so nothing extra to be done by standardisation which will convert the value to between -3 & 3. Also it will make us loose the intepretation of the dummy variable(here country and purchased col) i.e which country correspond to which after standardisation. Many say that applying standardisation on dummy variable may increase model performance but I have never seen anything which proves it.    

In [31]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train[:,3:] = scaler.fit_transform(x_train[:,3:]) # take all columns from age. fit computes mean and median of each value. transform apply formula to tranform them to Xstand
x_test[:,3:] = scaler.transform(x_test[:,3:])#Need to apply the same scaler on both train and test set to get same transformation 
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [32]:
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
