In [38]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [39]:
#import dataset
dataset = pd.read_csv('Data.csv') # Change this in the template
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [40]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [41]:
#convert 1D to 2D array
y=y.reshape(len(y),1)

In [42]:
print(y)


[[463.26]
 [444.37]
 [488.56]
 ...
 [429.57]
 [435.74]
 [453.28]]


In [43]:
#split data 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [44]:
#feature scaling 
from sklearn.preprocessing import StandardScaler
scalerX= StandardScaler()
scalerY= StandardScaler()
x_train = scalerX.fit_transform(x_train)
y_train = scalerY.fit_transform(y_train)

In [45]:
#train model 
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(x_train,y_train)

C:\Users\denni\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVR()

In [46]:
#predict results
y_pred = scalerY.inverse_transform(regressor.predict(scalerX.transform(x_test)))
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[434.05 431.23]
 [457.94 460.01]
 [461.03 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]


In [ ]:
#evaluate model performance - take the one with highest r 2 score 

In [47]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9480784049986258